### ISSUE TITLE
Looking forward to the release of the code and model!

### ISSUE THREAD

**Issue by jianghaojun** [microsoft/GLIP#1]

**Comment by Ariellsc** [comment]
> _No description provided._

+1

**Comment by iNeil77** [comment]
+1

**Comment by zyqdragon** [comment]
+1

**Comment by zyqdragon** [comment]
+1

**Comment by d12306** [comment]
+1, this paper is going to be a truck for sure!

**Comment by JarintotionDin** [comment]
+1

**Comment by bobwan1995** [comment]
+1

**Comment by JialianW** [comment]
Looking forward as well

**Comment by Edwardmark** [comment]
+1

**Comment by xiao2mo** [comment]
+1

**Comment by liunian-harold-li** [comment]
Thank everyone for your interest for our code and paper! My apologies for the long delay. The code is available now ; )

This is the first version and we will make some updates soon. Comments and issues are welcome!

**Comment by FrancescoSaverioZuppichini** [comment]
This is amazing! Thanks
