### ISSUE TITLE
GLIP-L fine tuning/training

### ISSUE THREAD

**Issue by aiotko** [microsoft/GLIP#13]
Hi, 

I've tried to run GLIP-L fine-tuning on COCO dataset and the estimate is around 44 days on GeForce RTX 3090 and 8 days on 4*A100 GPUs.

Could you please provide weights for the fine-tuned model and clarify whether the estimates are relevant or I do something wrong :-)?

**Comment by sadransh** [comment]
I need the same checkpoint if possible. 

@aiotko I am trying to start fine-tuning on coco using the following command I getting to `KeyError: 'embedded'`  when trying to fine-tune on coco with config and weights provided for largest model.

**Comment by aiotko** [comment]
@sadransh I was able to start fine-tuning for GLIP-L on 4 x A100 GPUs using the following command, the estimate shown is 8-9 days.

At the same time I'm unsure if the parameters are suitable as I just borrowed them from the script for tiny model and adjusted only the batch size.

Btw I've used cuda 11.6, pytorch 1.9.0+cu111 on Ubuntu 18.04.

```
python3.7 -m torch.distributed.launch --nproc_per_node=4 \
          tools/train_net.py \
          --config-file configs/pretrain/glip_Swin_L.yaml \
          --skip-test \
          MODEL.WEIGHT MODEL/glip_large_model.pth \
          DATASETS.TRAIN '("coco_grounding_train", )' \
          MODEL.BACKBONE.FREEZE_CONV_BODY_AT -1 \
          SOLVER.IMS_PER_BATCH 8 \
          SOLVER.USE_AMP True \
          SOLVER.MAX_EPOCH 24 \
          TEST.DURING_TRAINING False \
          TEST.IMS_PER_BATCH 8 \
          SOLVER.FIND_UNUSED_PARAMETERS False \
          SOLVER.BASE_LR 0.00001 \
          SOLVER.LANG_LR 0.00001 \
          SOLVER.STEPS \(0.67,0.89\) \
          DATASETS.DISABLE_SHUFFLE True \
          MODEL.DYHEAD.SCORE_AGG "MEAN" \
          TEST.EVAL_TASK detection
```

**Comment by liunian-harold-li** [comment]
Hi, indeed it is costly to fine-tune GLIP-L on COCO. 
If you are not aiming for the absolute highest performance or trying to squeeze out the last few points, usually fine-tuning for less steps still gives quite high performance. 

I will try to dig up the exact config we used for tuning the GLIP-L model on COCO. For achieving the SotA performance, we also need to increase the training resolution and use multi-scale testing for evaluation.
