### ISSUE TITLE
Query about word-region alignment score

### ISSUE THREAD

**Issue by tfc-0** [microsoft/GLIP#135]
Hi,

Thanks for the exciting work. I have a mall query: Does this line produce the region-word alignment scores S_ground mentioned in the paper?
Line: https://github.com/microsoft/GLIP/blob/main/maskrcnn_benchmark/modeling/rpn/vldyhead.py#L843

**Comment by inhaowu** [comment]
我觉得应该是的，前者代表的是图像的特征，后者代表文本的特征。

**Comment by liunian-harold-li** [comment]
Thank you for your interest in our work. Sorry for the delay in response!

Yes, this line produces the region-word alignment scores.
