### ISSUE TITLE
Runtime Error in Colab demo

### ISSUE THREAD

**Issue by NickChang97** [microsoft/GLIP#15]
Hi, really thanks for releasing so amazing work. But I encounter something unexpected in the colab demo. 

`image = load('http://farm4.staticflickr.com/3693/9472793441_b7822c00de_z.jpg')`

`caption = 'bobble heads on top of the shelf'`

`result, _ = glip_demo.run_on_web_image(image, caption, 0.5)`

`imshow(result, caption)`

When I run this codes above , "RuntimeError: Not compiled with GPU support" is reported, can you provide some advice?

**Comment by Haotian-Zhang** [comment]
Hi,

It seems like CUDA is not found when building the repo. You should make sure
`python -c 'import torch; from torch.utils.cpp_extension import CUDA_HOME; print(torch.cuda.is_available(), CUDA_HOME)'`

print (True, a directory with cuda) at the time you build

**Comment by NickChang97** [comment]
> RuntimeError: Not compiled 

> > Hi, really thanks for releasing so amazing work. But I encounter something unexpected in the colab demo.
> > `image = load('http://farm4.staticflickr.com/3693/9472793441_b7822c00de_z.jpg')`
> > `caption = 'bobble heads on top of the shelf'`
> > `result, _ = glip_demo.run_on_web_image(image, caption, 0.5)`
> > `imshow(result, caption)`
> > When I run this codes above , "RuntimeError: Not compiled with GPU support" is reported, can you provide some advice?
> 
> Hi,
> 
> It seems like CUDA is not found when building the repo. You should make sure `python -c 'import torch; from torch.utils.cpp_extension import CUDA_HOME; print(torch.cuda.is_available(), CUDA_HOME)'` print (True, a directory with cuda) at the time you build

Thanks for your quick reply, I got "True None", can you give further advice to solve this? Thanks in advance

**Comment by liunian-harold-li** [comment]
Hi, did you choose the runtime type with GPU support on Colab? Another possible reason is that the Colab demo attempts installing a specific CUDA version on Colab, which may not work if the GPU type you get is different from mine. 

Please consider running the demo locally (this way, you could use docker and do not need to bother with the cuda installation) or retry to see if you could get a different GPU that works.

**Comment by NickChang97** [comment]
Really thanks for your reply, I will try it according to your advice.
