### ISSUE TITLE
The link of annotation for Objects365 cannot be opened :https://penzhanwu2bbs.blob.core.windows.net/data/GLIPv1_Open/Objects365/objects365_train_vgoiv6.cas2000.yaml

### ISSUE THREAD

**Issue by yeppp27** [microsoft/GLIP#155]

**Comment by ko4ro** [comment]
@yeppp27  Same problem for me.

Did you find the yaml file？

**Comment by taoxunqiang** [comment]
Same problem.

**Comment by yongwangy91** [comment]
Anyone who knows how to acces the files listed in : https://penzhanwu2bbs.blob.core.windows.net/data/GLIPv1_Open/Objects365/objects365_train_vgoiv6.cas2000.yaml? Even using azure storage explorer, I cannot get it.
