### ISSUE TITLE
What is the difference of provided `lvis_od_val.json` and official `lvis_v1_val.json`

### ISSUE THREAD

**Issue by Kyfafyd** [microsoft/GLIP#19]
Dear authors, thanks for your nice work and codes!
I would like to learn what is the difference of provided `lvis_od_val.json` and official `lvis_v1_val.json`?

**Comment by Haotian-Zhang** [comment]
@Kyfafyd Thank you for your question. `lvis_od_val.json` is almost the same as the officially provided `lvis_v1_val.json`, besides a slight difference in format (list vs. dict).
