### ISSUE TITLE
Why is contrastive loss not used in pretraining?

### ISSUE THREAD

**Issue by PanXiebit** [microsoft/GLIP#21]
https://github.com/microsoft/GLIP/blob/fd52c6361f013e70ae7682d90b3ab3ca2bd5e6bc/configs/pretrain/glip_Swin_T_O365.yaml#L40

In the config of pretraining, why set the USE_CONTRASTIVE_ALIGN_LOSS  False?

**Comment by Haotian-Zhang** [comment]
> https://github.com/microsoft/GLIP/blob/fd52c6361f013e70ae7682d90b3ab3ca2bd5e6bc/configs/pretrain/glip_Swin_T_O365.yaml#L40
> 
> In the config of pretraining, why set the USE_CONTRASTIVE_ALIGN_LOSS False?

Hi @PanXiebit, thank you for the question. The dot product loss is actually the grounding loss which we refer to in our paper. The contrastive align loss here in the code is mentioned in the MDETR paper, and we do not use it. For more details about the contrastive alignment loss, please check the corresponding paper. Thanks!
