### ISSUE TITLE
GLIP demo issue in colab

### ISSUE THREAD

**Issue by neerajdr** [microsoft/GLIP#29]
I am getting isssue

[/content/GLIP/maskrcnn_benchmark/engine/predictor_glip.py](https://localhost:8080/#) in overlay_entity_names(self, image, predictions, names, text_size, text_pixel, text_offset, text_offset_original)
    345 
    346             cv2.putText(
--> 347                 image, s, (int(x), int(y)-text_offset_original), cv2.FONT_HERSHEY_SIMPLEX, text_size, (self.color, self.color, self.color), text_pixel, cv2.LINE_AA
    348             )
    349             previous_locations.append((int(x), int(y)))

AttributeError: 'GLIPDemo' object has no attribute 'color'

**Comment by Haotian-Zhang** [comment]
Please refer to #31 for more details, thanks!

**Comment by eadst** [comment]
change "(self.color, self.color, self.color)" to "(255, 255, 255)"
