### ISSUE TITLE
Do you use alignment loss?

### ISSUE THREAD

**Issue by Colin97** [microsoft/GLIP#30]
In the paper, you introduced text-region alignment loss. However, in the config files, USE_CONTRASTIVE_ALIGN_LOSS are set to FALSE. Is there any explanation for not using it?

**Comment by Haotian-Zhang** [comment]
@Colin97 Thank you for the question. Please refer to #21 for more details.

**Comment by Colin97** [comment]
Thanks for the timely reply!
