### ISSUE TITLE
INPUT parameter in cfg (for example "Aquarium_Aquarium_Combined.v2-raw-1024.coco.yaml")

### ISSUE THREAD

**Issue by patrickESM** [microsoft/GLIP#32]
Hello, 

thanks for your awesome work and that you provide the code here on github!

I have a quick question about the INPUT parameter in the cfg files:

for example:
`INPUT:
  MIN_SIZE_TRAIN: 800
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333`

Could you please elaborate what this parameter does?

Does this define the maximum input size of the network?
For example if my images of a custom dataset are 2560x1440, does this parameter downscale them to width=1333?
And if i had smaller images would this upscale them to 800?

Also does the parameter "min_image_size" of GLIP_demo
`glip_demo = GLIPDemo(
    cfg,
    min_image_size=800,
    confidence_threshold=0.5,
    show_mask_heatmaps=False
)`
define the input size of the images during inference?

The reason Iask is the following :
When I promp finetuned my custom dataset i used the following INPUT parmeter : all set to 2560. The training worked fine and the results where good.
then I used GLIP_demo to infer them and watch the output. Her i used  min_image_size=2560, and i got OOM error. 

thank you for your reply!
Patrick

**Comment by weinman** [comment]
Yeah, this part is not particularly intuitive. You can see how these parameters get used [here](https://github.com/microsoft/GLIP/blob/fd52c6361f013e70ae7682d90b3ab3ca2bd5e6bc/maskrcnn_benchmark/data/transforms/transforms.py#L84) (as called from [here](https://github.com/microsoft/GLIP/blob/fd52c6361f013e70ae7682d90b3ab3ca2bd5e6bc/maskrcnn_benchmark/engine/predictor_glip.py#L84) in the demo).

Generally: It will set the smaller dimension of the image to whatever is given as the min. 

Two things to observe in practice:
* If you're using this parameter with finetuning, there's a good chance it's getting overridden by the `--config-file` setting, even if you have a custom config file for `--ft-tasks`. (I never looked into how it was actually set or how to fix that, but I confirmed it by simply printing the value from the Resize transform and finding it to be the original list of sizes in the "parent" config) 
* The min test size likely automatically resizes all your test/evaluation images, which you may not want. Consider removing this transform with something like this:

```
 diff --git a/maskrcnn_benchmark/data/transforms/build.py b/maskrcnn_benchmark/data/transforms/build.py
index 9f66c09..13155c5 100644
--- a/maskrcnn_benchmark/data/transforms/build.py
+++ b/maskrcnn_benchmark/data/transforms/build.py
@@ -33,13 +33,22 @@ def build_transforms(cfg, is_train=True):
     normalize_transform = T.Normalize(
         mean=cfg.INPUT.PIXEL_MEAN, std=cfg.INPUT.PIXEL_STD, format=input_format
     )
- 
-    transform = T.Compose(
-        [
-            T.Resize(min_size, max_size, restrict=fix_res),
-            T.RandomHorizontalFlip(flip_horizontal_prob),
-            T.ToTensor(),
-            normalize_transform,
-        ]
-    )
+
+    if is_train:
+        transform = T.Compose(
+            [
+                T.Resize(min_size, max_size, restrict=fix_res),
+                T.RandomHorizontalFlip(flip_horizontal_prob),
+                T.ToTensor(),
+                normalize_transform,
+            ]
+        )
+    else:
+        transform = T.Compose(
+            [
+                T.ToTensor(),
+                normalize_transform,
+            ]
+        )
+
     return transform
```

**Comment by patrickESM** [comment]
Thank you very much! @weinman 

That made the parameters way clearer to me
