### ISSUE TITLE
MAP dataset-wise for ODinw

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [microsoft/GLIP#35]
Dear all,

I hope to find you well. Thanks for the fantastic work and for releasing GLIP to the world :) 

I am working at Robolow and we are excited you use our hosted datasets to build ODinw. We would like to know if you can share the MAP per dataset and not only the average. This would help us understand the performance on some datasets with a substantial domain shift compared with the training data.

Thanks a lot and looking forward to GLIP-v2 :)

Cheers,

Francesco

**Comment by Haotian-Zhang** [comment]
@FrancescoSaverioZuppichini Thank you for the support and the provided datasets! We do have a detailed table in the Appendix of the GLIP paper, where we put the mAP for various models for every 13 datasets there. Thank you!

**Comment by FrancescoSaverioZuppichini** [comment]
@Haotian-Zhang Thanks a lot!

**Comment by FrancescoSaverioZuppichini** [comment]
@Haotian-Zhang Any chance you also got the `mAP(iou=0.50)`  and not  `mAP(iou=0.50:0.95)`. Thank you a lot
