### ISSUE TITLE
hi，I want to test a dataset with 200 classes,but get a error

### ISSUE THREAD

**Issue by weveng** [microsoft/GLIP#37]

**Comment by weveng** [comment]
RuntimeError: The expanded size of the tensor (1024) must match the existing size (512) at non-singleton dimension 1.  Target sizes: [1, 1024].  Tensor sizes: [1, 512]

**Comment by weveng** [comment]
i want to know if the model can test the dataset with 200 classes

**Comment by xugy16** [comment]
I think the default max class  number is 80

**Comment by Haotian-Zhang** [comment]
@weveng @xugy16 There is actually no "max class" concept in GLIP since it is an open-vocabulary contextualized object grounding method. Please just make sure that after converting 200 classes into one detection prompt, it will not exceed the maximum length of the input for the text encoder. If the prompt exceeds the length, you can take a look at the codes about how we deal with the LVIS dataset (~1200 classes).

**Comment by weinman** [comment]
@Haotian-Zhang  Thank you for this tip! 

I see from the paper that the prompt is split up for training (Appendix B, "When not all object categories can fit into a single prompt") and evaluation (Appendix C.2). 

This makes a lot of sense.

Unfortunately, I cannot find the relevant routines in the code. I wonder if someone can more specifically refer us to where should @weveng and I be looking for the implementation of these splits/accumulations for training and testing?

**Comment by small-code-cat** [comment]
> @Haotian-Zhang Thank you for this tip!
> 
> I see from the paper that the prompt is split up for training (Appendix B, "When not all object categories can fit into a single prompt") and evaluation (Appendix C.2).
> 
> This makes a lot of sense.
> 
> Unfortunately, I cannot find the relevant routines in the code. I wonder if someone can more specifically refer us to where should @weveng and I be looking for the implementation of these splits/accumulations for training and testing?

I haven't found the corresponding code either. Can you find a way to handle situations where the prompt length is too long？
