### ISSUE TITLE
'GLIPDemo' object has no attribute 'color'

### ISSUE THREAD

**Issue by xugy16** [microsoft/GLIP#39]
when calling self.overlay_entity_names(result, top_predictions),

cv2.putText(
                image, s, (int(x), int(y)-text_offset_original), cv2.FONT_HERSHEY_SIMPLEX, text_size, (self.color, self.color, self.color), text_pixel, cv2.LINE_AA
            )
self.color is not intilized. 

When running demo.

color is initilied in visualize_with_predictions, which is not called in demo.

**Comment by weinman** [comment]
See #31 or #27 for possible fixes.
