### ISSUE TITLE
how to inference single image and how to visualize the result?

### ISSUE THREAD

**Issue by Edwardmark** [microsoft/GLIP#4]
Hi， your great work impressed me a lot, could you please provide the code to inference single image and visulization? Thanks.

**Comment by liunian-harold-li** [comment]
Hi we have provided a demo at https://colab.research.google.com/drive/12x7v-_miN7-SRiziK3Cx4ffJzstBJNqb?usp=sharing.

**Comment by Edwardmark** [comment]
> https://colab.research.google.com/drive/12x7v-_miN7-SRiziK3Cx4ffJzstBJNqb?usp=sharing

![image](https://user-images.githubusercontent.com/15247551/166857232-a66e7f5b-c481-40c1-970c-861dccaef218.png)
hi, I run the demo in Colab, with all the previous step running successful, this step failed with error "not compiled with gpu support". Please help, thanks.

**Comment by Edwardmark** [comment]
@liunian-harold-li hi, how to set config.yaml to  inference like your demo (https://colab.research.google.com/drive/12x7v-_miN7-SRiziK3Cx4ffJzstBJNqb?usp=sharing)when using the prompt_finetune folloing readme.

**Comment by Edwardmark** [comment]
@liunian-harold-li In other words, what config should be changed in glip_swin_l.yaml to inference the model after prompt-finetuning. Thanks.

**Comment by patrickESM** [comment]
+1

**Comment by tkdguraa** [comment]
I had the same problem, but I fixed the inference.py part a little bit to solve the problem. I hope this code helps.

https://github.com/tkdguraa/GLIP

**Comment by tkdguraa** [comment]
> > I had the same problem, but I fixed the inference part a little bit to solve the problem. I hope this code helps.
> > https://github.com/tkdguraa/GLIP
> 
> Please tell me which python file and how to run, thank you！

Run OD_Demo.ipynb file, it works well for me.
For the changed code, you can refer to the file “maskrcnn_benchmark/engine/predictor_glip.py“.

**Comment by eliabntt** [comment]
Personally, I simply changed in `predictor_glip.py:run_ner` into
```
                for m in re.finditer(rf'\b{entity}\b', caption.lower()):
                    tokens_positive.append([[m.start(), m.end()]])
```

this will only do exact matches so if you have two categories "A" and "As" it won't duplicate the matches (which was the source of the issue and the only noticeable difference I saw while debugging between @tkdguraa code and mine)
