### ISSUE TITLE
Can we have a Gradio demo of GLIPv2 ?

### ISSUE THREAD

**Issue by MohamedAliRashad** [microsoft/GLIP#42]
Something on huggingface will be nice.

**Comment by Haotian-Zhang** [comment]
@MohamedAliRashad Working on it and hopefully it will be released soon!

**Comment by Haotian-Zhang** [comment]
Just a quick update, we are working with HuggingFace to get a GPU to host our demo on Gradio. Hopefully, the demo for GLIPv1 will be released soon!

**Comment by MohamedAliRashad** [comment]
@Haotian-Zhang This is excellent news.

Good Luck and shall v2 follow soon.

**Comment by Haotian-Zhang** [comment]
We have updated the [HuggingFace Demo](https://huggingface.co/spaces/haotiz/glip-zeroshot-demo) for GLIP. Please feel free to give it a try! The v2 pre-training codes and demos will also be released soon, please stay tuned.

**Comment by SKBL5694** [comment]
> We have updated the [HuggingFace Demo](https://huggingface.co/spaces/haotiz/glip-zeroshot-demo) for GLIP. Please feel free to give it a try! The v2 pre-training codes and demos will also be released soon, please stay tuned.

It looks like there is some bug in huggingface's example, I found you give 6 examples in huggingface. In the 4th example, the model gives the wrong bounding boxes in "A blue dress. An orange shirt". It looks like the model got the colors wrong.

**Comment by SKBL5694** [comment]
To be more precise, I think the model will reverse the orange and blue. I test it on some other pictures and find this bug.

**Comment by Haotian-Zhang** [comment]
@SKBL5694 Thank you for pointing out the bugs! The reason is due to the RGB channel of the image is reversed to BGR. I have updated the demo, and I think the results are correct now. Thanks!
