### ISSUE TITLE
Can we run visualization code without evaluation and using self vocab list?

### ISSUE THREAD

**Issue by FrankFcc** [microsoft/GLIP#43]
Thanks for the amazing work and I'm really excited about that! Currently, I am trying to run the inference with your pretrained-model but had a question that if I can run visualization with prediction without the evaluation part. Is that possible in current codebase?

**Comment by Haotian-Zhang** [comment]
@FrankFcc Thank you for your interest! Yes, we have a Colab demo here to help you run the demo without the evaluation. Please check out: https://colab.research.google.com/drive/12x7v-_miN7-SRiziK3Cx4ffJzstBJNqb?usp=sharing#scrollTo=BtMdw_J6PprI. A huggingface Gradio demo is still under preparation, but will be released soon.

**Comment by FrankFcc** [comment]
Hi @Haotian-Zhang , 
Thanks you so much for your quick response. I've already utilized your demo code on Colab and it did give us some promising predictions. Then, I'm currently trying to use pretrained model via GLIP in our own cluster and also trying to set up a possible pipeline to our own custom data vocab and frame.  As a result, I wonder if GLIP team already had some built-in functions like inside visualize_grounding_net.py to skip the evaluation process and allow process lots of images with our own GPUs to perform speed check or visualize result. 
Thanks you so much for spending time reading my issue and I hope my question won't waste you so many time.

**Comment by Haotian-Zhang** [comment]
Hi @FrankFcc, if you check about the demo in detail. It is indeed a well-built pipeline to feed in your custom images and texts and then visualize the outputs. I can point to the https://github.com/microsoft/GLIP/blob/c5063c2fbff0482d5c6df7ac801ffd2921923e70/maskrcnn_benchmark/engine/predictor_glip.py#L27. Please take a look at this class and the function https://github.com/microsoft/GLIP/blob/c5063c2fbff0482d5c6df7ac801ffd2921923e70/maskrcnn_benchmark/engine/predictor_glip.py#L134 is what you need.
