### ISSUE TITLE
Pretrained model weights without the deep fudsion module

### ISSUE THREAD

**Issue by bobwan1995** [microsoft/GLIP#44]
Hi, thanks for your great work! I really enjoy reading your paper. 
I'm wondering if you could release the model weights pre-trained only on GoldG & Cap24M datasets without the deep fusion module (both GLIP-T & GLIP-L). We want to have some ablative experiments on that setting. Thank you so much!

**Comment by Haotian-Zhang** [comment]
Hi @bobwan1995 , thank you for your interest! Sorry, we don't have a pre-trained model with GoldG & Cap24M without deep fusion. We only conducted experiments on models with deep fusion modules after we verified their effectiveness on tiny models with a small OD dataset.
