### ISSUE TITLE
Error in GLIP Colab and question

### ISSUE THREAD

**Issue by fepegar** [microsoft/GLIP#45]
Hi! Thanks for this repo. This is just a heads-up that the Colab for GLIP is not working as it complains about `% cd`. If replaced with `%cd`, it's all good.

I also have a question. I tried setting `show_mask_heatmaps` to `True` and got an error. What should I change for this to work?

**Comment by liunian-harold-li** [comment]
Thank you for the heads-up! 

Currently the Colab demo only supports detection and not segmentation yet. Segmentation is supported in GLIPv2.

**Comment by fepegar** [comment]
I though there were heatmaps available for the detection problem as well. Thanks for your reply!
