### ISSUE TITLE
It seems that the docker environment（pytorch:ubuntu20.04_torch1.9-cuda11.3-nccl2.9.9） has some bugs

### ISSUE THREAD

**Issue by SKBL5694** [microsoft/GLIP#46]
I find the torch version in the docker is "1.9.0a0+c3d40fd", but when I run the code it raise a error: ·module `torch.nn.functional' has no attribute 'mish'` . In the other docker environment, the torch version is 1.9.1 and it has no error at that position.
What confuses me is that I can see the 'mish' function in version 1.9.0 in the official pytorch documentation. I'm not sure how to find the source code about the "1.9.0a0+c3d40fd".

**Comment by patrickESM** [comment]
I had the same issue yesterday after rebuilding my own Docker Container.

The problem seems to be with the transformers pip package.

I switched back to an older transformers version. For example:

`pip install transformers==4.20.1`

This worked for me.

**Comment by SKBL5694** [comment]
> I had the same issue yesterday after rebuilding my own Docker Container.
> 
> The problem seems to be with the transformers pip package.
> 
> I switched back to an older transformers version. For example:
> 
> `pip install transformers==4.20.1`
> 
> This worked for me.

Actually, I thought about the problem of transformers. However I went to look at the mish method call of the previous version of the transformers and I found the same as the current version, so I didn't try the historical version of the transformers. Now I will go back and try it, thanks :)

**Comment by Haotian-Zhang** [comment]
@patrickESM Thank you for your solutions. I will close the issue now, please feel free to re-open it if any problems.
