### ISSUE TITLE
text encoder for detection

### ISSUE THREAD

**Issue by mactavish91** [microsoft/GLIP#50]
Hello, the author, great work! However, there's one detail that makes me very confused: The input length of the language encoder is limited (e.g. 512), but when there are many categories to be detected, up to thousands of categories(e.g. LVIS), how to input the detected categories into the model? And will the attention module in the language encoder cause some words to be ignored, thus affecting the detection performance?

**Comment by Haotian-Zhang** [comment]
Hi @mactavish91 , we have already taken this into account when we are dealing with LVIS. If the prompt exceeds the encoder length, we divide the whole prompt into various queries, and we do the aggregation before the evaluation. Please refer to https://github.com/microsoft/GLIP/blob/b28a840070f5c60d2cea23b252280eb0fda0dfee/maskrcnn_benchmark/engine/inference.py#L455 for more details.

**Comment by mactavish91** [comment]
@Haotian-Zhang  Thank you for your kindly help! Besides, is glip-v2 open source now?

**Comment by GG-Bonds** [comment]
I have the same question

> Hi, in this scenario, is there a possibility that a single object is detected twice? For example, if the model makes a mistake and detects a kite as a "plane" (when queried for plane), and then it also detects it as a "kite", will the model return two bounding boxes (one for plane, another for kite) for the same object? This is assuming that the words "plane" and "kite" are in different divisions of the prompt. Thanks!
