### ISSUE TITLE
keypoint detection

### ISSUE THREAD

**Issue by neerajdr** [microsoft/GLIP#56]
Can glip code be used for keypoint detection and and if yes whats the starting point?

**Comment by Haotian-Zhang** [comment]
@neerajdr Thank you for your question. I believe our codes can be adapted to do the keypoint detection with minor changes. Please refer to some papers or open-source codes about how to add a keypoint head onto the one-stage detector. Then, to fine-tune the keypoint head on specific keypoints datasets. I guess that will work.
