### ISSUE TITLE
prompt fine-tuning

### ISSUE THREAD

**Issue by raymond1123** [microsoft/GLIP#60]
Hi author, thanks for this great job!
I am just wondering when Prompt Tuning, as mentioned in the paper: "_we first get prompt embeddings P0 from the language backbone, then discard the language backbone and only fine-tune P0 as the task- specific input_", whether O0 will also be fine-tuned?

**Comment by Haotian-Zhang** [comment]
Hi @raymond1123, thank you for your questions. The embedding P consists of two embeddings: (1) the initial embeddings from pre-trained text encoder P_0 and (2) an offset embedding P_offset (initialized as all zeros) that needs to be fine-tuned during the task-specific tunings. To answer your questions, the P_0 will not be changed during the fine-tuning, but P_offset will be changed.

**Comment by Haotian-Zhang** [comment]
@raymond1123 Great, I'll close the issue now. Feel free to open it if any further questions.
