### ISSUE TITLE
adjust GLIP to pytorch1.11.0 or higher version

### ISSUE THREAD

**Issue by SunzeY** [microsoft/GLIP#76]
maskrcnn_benchmark is still using `THC`, however this module has already been removed in the latest pytorch version like `torch1.11.0` this will cause compile error when install maskrcnn_benchmark as dynamic library.
for example, in `maskrcnn_benchmark/csrc/cuda/ROIAlign_cuda.cu`
```C
#include <THC/THC.h>
#include <THC/THCAtomics.cuh>
#include <THC/THCDeviceUtils.cuh>
```
I recommended make some adjustment to this changes

**Comment by SunzeY** [comment]
@amira-essawy No. you have to use lower version of pytorch as both runtime and compile environment.

**Comment by amira-essawy** [comment]
@SunzeY I tried using the provided containers but I still have the same problem. Have you managed to run it?

**Comment by SunzeY** [comment]
@amira-essawy sorry, I didn't try the provided environment. I recommend find same issue in [mask_rcnn_benchmark](https://github.com/facebookresearch/maskrcnn-benchmark) to solve this problem.

**Comment by WHY-student** [comment]
[issue](https://github.com/pytorch/pytorch/issues/72807#issuecomment-1699371013), maybe this answer can solve the problem. I solve it.
