### ISSUE TITLE
How to use negative samples to train the model?

### ISSUE THREAD

**Issue by Edwardmark** [microsoft/GLIP#8]
Hi, in detection there is lots of false positive, for examples, when we want to detect human-face, some animal face or cartoon face is detected as false negatives, so we need add the negative samples to training data.

But I found that in training, this negative data without annotations will be ignored, could you please tell me the right way to add this negative data ? Thanks.

**Comment by liunian-harold-li** [comment]
We followed the common practice in COCO training where negative data (images without any boxes) will be ignored. 

If you want to train on images without any boxes, you could start by removing these lines https://github.com/microsoft/GLIP/blob/main/maskrcnn_benchmark/engine/trainer.py#L95.

But the assumption that we will only train on images with some boxes is made in a lot of places in the code and I cannot recall all the places that need to be modified.

**Comment by Edwardmark** [comment]
@liunian-harold-li Thanks. I will try.

**Comment by nanfei666** [comment]
> @liunian-harold-li Thanks. I will try.

@Edwardmark Hi do you figure a way to adding the negative samples during training?
